// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

// Defines values for OrderItem.
const (
	TeaTableGreen OrderItem = "Tea Table Green"
	TeaTableRed   OrderItem = "Tea Table Red"
)

// Order defines model for Order.
type Order struct {
	Id    *string   `json:"id,omitempty"`
	Item  OrderItem `json:"item"`
	Price int       `json:"price"`
}

// OrderItem defines model for Order.Item.
type OrderItem string

// PutOrderIdJSONBody defines parameters for PutOrderId.
type PutOrderIdJSONBody = Order

// PutOrderIdJSONRequestBody defines body for PutOrderId for application/json ContentType.
type PutOrderIdJSONRequestBody = PutOrderIdJSONBody
